import os

claude_content = """<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Claude & Prompt Engineering | AI for All</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Fira+Code:wght@400;500&display=swap" rel="stylesheet">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <link rel="stylesheet" href="styles.css?v=4">
</head>
<body>
    <div class="app-container">
        <!-- Sidebar placeholder (Assume sidebar is already updated, we will just use a generic placeholder and rely on our previous python script or assume the user will keep the sidebar intact. Wait, it's safer to read the sidebar from index.html and inject it. Let's do that in python). -->
"""

rag_content = """<!DOCTYPE html>
<html lang="en" data-theme="dark">
"""

# Actually, rather than building the entire HTML as a string inside a python script, I can just use `write_to_file` to write out the full HTML for `claude.html`. But wait, I need to make sure I don't lose the sidebar!
# The sidebar was generated by `update_sidebar_v3.py`.
# Let's write a python script `rewrite_modules.py` that reads the sidebar from `index.html`, and then uses it to write out full `claude.html`, `rag.html`, etc.
